// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBTxz58haFRnYUS3rjK2iJsepiTsncvk',
    appId: '1:931041863253:android:2885e551d7e009a94496dc',
    messagingSenderId: '931041863253',
    projectId: 'mysuperbrain-ddec7',
    storageBucket: 'mysuperbrain-ddec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHZk-MwvleCqEIh8YVE6ch2QD5536WCo',
    appId: '1:931041863253:ios:fd14b77eb8065e734496dc',
    messagingSenderId: '931041863253',
    projectId: 'mysuperbrain-ddec7',
    storageBucket: 'mysuperbrain-ddec7.appspot.com',
    iosBundleId: 'com.grapplesoft.msbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHZk-MwvleCqEIh8YVE6ch2QD5536WCo',
    appId: '1:931041863253:ios:a36dfe42c3d4c27b4496dc',
    messagingSenderId: '931041863253',
    projectId: 'mysuperbrain-ddec7',
    storageBucket: 'mysuperbrain-ddec7.appspot.com',
    iosBundleId: 'com.grapplesoft.msb',
  );

}